### ISSUE TITLE
Balance Bäume

### ISSUE THREAD

**Issue by Jost-Boy** [RWetenkamp/algokomp#1]
Hey, 
auf Seite 71 bei der Lösung zu Aufgabe 1 ist mir meinem Verständnis nach ein Fehler aufgefallen. 
Die Balance vom Knoten K ist doch 0 und nicht 1 oder?  Da Balance laut VL h(RT)-h(LT) ist

LG

**Comment by romanwtk** [comment]
Hey, vielen Dank fürs Anmerken! 👍 
Also wir gehen ja von unten nach oben vor, d.h. die Knoten W und H haben jeweils die Balance 0 (es sind ja Blätter), T hat dann die Balance 1 (1-0 =1). Dann hätten wir für die Balance von K = h(T) - h(H) = 1 - 0 = 1.
Insofern macht die 1 da - meiner Meinung nach zumindest durchaus Sinn. :)
Oder gingst du von dem Baum aus, in dem du schon J hinzugefügt hast? Dann wäre es tatsächlich 0.

**Comment by Jost-Boy** [comment]
Hey, ja ich ging von aus als J schon hinzugefügt war. 

Andersrum macht deines natürlich auch Sinn. Würde sagen wir haben beide Recht bloß aus anderen blickwinkeln

**Comment by romanwtk** [comment]
Okay, perfekt! :) Dann präzisiere ich die Aufgabenstellung noch ein bisschen, damit auch alle eins nach dem anderen erledigen und wir über das gleiche sprechen. Dankeschön! 😄
